In [1]:
import numpy as np

In [18]:
inds = np.random.permutation(28)
inds_validation = inds[:5]
inds_training = inds[5:]

In [15]:
x = np.zeros(shape=(28, 8))  # Fake inputs

In [16]:
inds_validation

array([22, 15,  3, 23,  0])

In [17]:
inds_training

array([10, 18,  9, 21, 13, 25,  7, 11, 14, 17, 27, 16,  4,  5,  8, 26, 12,
       24,  6, 20,  2, 19,  1])

In [19]:
x[inds_validation,:]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
x[inds_training,:]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
model.fit(x_training, y_training)

NameError: name 'model' is not defined

In [23]:
y_pred = model.predict(x_validation)

NameError: name 'model' is not defined

In [24]:
np.sum(np.pow(y_validation - y_pred, 2))  # sum squared error

AttributeError: module 'numpy' has no attribute 'pow'

In [ ]:
np.sum(np.pow(y_validation - y_pred, 2))/5   # MSE